{
 "title": "5G UE Monitoring",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "UE",
    "query": "SELECT \"ueId\" FROM (SELECT \"ueId\",\"value\" FROM \"default.ssbRsrp\" WHERE time > now() - 1m )"
   },
   {
    "name": "Cell",
    "query": "SELECT \"cellId\" FROM (SELECT \"cellId\",\"value\" FROM \"default.ssbRsrp\" WHERE time > now() - 1m )"
   }
  ]
 },
 "panels": [
  {
   "title": "Total Number of UEs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "max",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default.ssbRsrp",
     "query": "SELECT count(distinct(\"ueId\")) FROM (select * from \"default.ssbRsrp\" WHERE (\"cellId\" =~ /^$Cell$/) and time> now()-10s)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$Cell$/" }
     ]
    }
   ]
  },
  {
   "title": "SSB RSRP",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_cellId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default.ssbRsrp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "SSB RSRQ",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_cellId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default.ssbRsrq",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "SSB SINR",
   "type": "graph",
   "gridPos": { "h": 8, "w": 23, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_cellId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cellId" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "default.ssbSinr",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$Cell$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  }
 ]
}