# Default values for acc-common.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: accelleran/cw-inst
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets:
  - name: accelleran-secret
nameOverride: ""
fullnameOverride: ""

# Overrides the number of deployment replicas
# replicaCount: 1

# spareInstanceCount specifies the number of spare deployment replicas (added together with the number of DUs)
spareInstanceCount: 0

# Application Settings
# cmd: "./cellWrapperInstanceAppl.exe"
cmd: "./cellWrapperInstanceAppl.exe"

args: []
#  - name: "--own"
#    value: 127.0.0.2

nats:
  url: "ric-nats-5g"
  port: "4222"

redisConfig:
  hostname: "ric-redis-5g"
  port: "6379"

bootstrapId: "cw-1"
bootstrapFile: /home/accelleran/5G/bootstrap.txt

jaegerAgentHost: "ric-jaeger-agent"

extraEnvs:
  - name: __APPNAME
    value: cellWrapperInstance

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: 
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 0
  privileged: true

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

draxNodeSelectorEnabled: "false"

draxNodeSelector:
  draxName: "main"

tolerations: []

affinity: {}

secrets:
  sshKey: "cw-ssh-key"

baseConfig:
  configDir: "/home/accelleran/5G/config"
  du:
    effnet:
      file: "duEffnetConfig.json"
      data: null
  l1:
    phluido:
      file: "l1PhluidoConfig.cfg"
      data: null
