{
 "title": "Cell Monitoring",
 "description": "Monitors the basic KPIs reported by RIC",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "ue", "query": "UE004" },
   { "name": "granularity", "query": "fifteen_minute" }
  ]
 },
 "panels": [
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Kbits" }
   ],
   "targets": [
    {
     "aggregators": [
      {
       "fieldName": "throughputReport.dlThroughput",
       "hidden": true,
       "name": "dlThroughputS",
       "type": "doubleSum"
      },
      {
       "hidden": true,
       "name": "dlThroughputC",
       "type": "count"
      }
     ],
     "alias": "$tag_ueRicId",
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "$granularity",
     "druidDS": "test2",
     "filters": [
      { "dimension": "throughputReport.ueRicId", "type": "selector", "value": "$ue" }
     ],
     "limit": 5,
     "measurement": "throughput",
     "postAggregators": [
      {
       "fields": [
        { "fieldName": "dlThroughputS", "type": "fieldAccess" },
        { "fieldName": "dlThroughputC", "type": "fieldAccess" }
       ],
       "fn": "/",
       "name": "dlThroughput",
       "type": "arithmetic"
      }
     ],
     "select": [
      [
       { "params": [ "dlthroughput" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "ueRicId", "operator": "=~", "value": "/^$ue$/" }
     ]
    }
   ]
  },
  {
   "title": "Serving Cell",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregators": [
      { "fieldName": "ueMeasurement.ueCellId", "name": "cellId", "type": "stringLast" }
     ],
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "$granularity",
     "druidDS": "test2",
     "filters": [
      { "dimension": "ueMeasurement.ueRicId", "type": "selector", "value": "$ue" }
     ],
     "limit": 5
    }
   ]
  },
  {
   "title": "Number of Cells",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregators": [
      {
       "fieldName": "ueMeasurement.cellId",
       "fieldNames": "ueMeasurement.cellId",
       "hidden": false,
       "name": "number",
       "type": "cardinality"
      }
     ],
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "$granularity",
     "druidDS": "test2",
     "filters": [
      {
       "dimension": "ueMeasurement.cellId",
       "negate": true,
       "type": "selector",
       "value": ""
      }
     ],
     "limit": 5,
     "measurement": "existence",
     "query": "SELECT COUNT(DISTINCT(\"cellId\") ) FROM (SELECT \"cellId\",allOnAir FROM \"cell_info\" WHERE time > now() - 5s) where allOnAir = 1",
     "select": [
      [
       { "params": [ "ue" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Number of UEs",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "aggregators": [
      { "fieldNames": "ueMeasurement.ueRicId", "name": "number", "type": "cardinality" }
     ],
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "$granularity",
     "druidDS": "test2",
     "filters": [
      {
       "dimension": "ueMeasurement.ueRicId",
       "negate": true,
       "type": "selector",
       "value": ""
      }
     ],
     "limit": 5
    }
   ]
  },
  {
   "title": "RSRP",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregators": [
      { "fieldName": "ueMeasurement.rsrp", "name": "rsrp", "type": "longMax" }
     ],
     "alias": "RSRP $tag_cellId",
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "$granularity",
     "druidDS": "test2",
     "filters": [
      { "dimension": "ueMeasurement.ueRicId", "type": "selector", "value": "$ue" },
      { "dimension": "ueMeasurement.attached", "type": "selector", "value": "1" }
     ],
     "limit": 5,
     "measurement": "measurement",
     "query": "SELECT \"rsrp\" FROM \"measurement\" WHERE (\"ueRicId\" =~ /^$ue$/) AND $timeFilter GROUP BY \"cellId\", \"ueRicId\"",
     "select": [
      [
       { "params": [ "rsrp" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ueRicId", "operator": "=~", "value": "/^$ue$/" }
     ]
    }
   ]
  },
  {
   "title": "RSRQ",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "aggregators": [
      { "fieldName": "ueMeasurement.rsrq", "name": "rsrq", "type": "longMax" }
     ],
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "$granularity",
     "druidDS": "test2",
     "filters": [
      { "dimension": "ueMeasurement.ueRicId", "type": "selector", "value": "$ue" },
      { "dimension": "ueMeasurement.attached", "type": "selector", "value": "1" }
     ],
     "limit": 5,
     "measurement": "measurement",
     "select": [
      [
       { "params": [ "rsrq" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ueRicId", "operator": "=~", "value": "/^$ue$/" }
     ]
    }
   ]
  },
  {
   "title": "CQI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "aggregators": [
      {
       "fieldName": "cqiReport.widebandCqi",
       "hidden": true,
       "name": "cqiS",
       "type": "longSum"
      },
      {
       "hidden": true,
       "name": "cqiC",
       "type": "count"
      }
     ],
     "alias": "Channel $tag_channel",
     "currentAggregator": { "type": "count" },
     "currentFilter": { "type": "selector" },
     "currentPostAggregator": { "fn": "+", "type": "arithmetic" },
     "currentSelect": { "dimension": "", "metric": "" },
     "customGranularity": "$granularity",
     "druidDS": "test2",
     "filters": [
      { "dimension": "cqiReport.ueRicId", "type": "selector", "value": "$ue" }
     ],
     "limit": 5,
     "measurement": "cqi",
     "postAggregators": [
      {
       "fields": [
        { "fieldName": "cqiS", "type": "fieldAccess" },
        { "fieldName": "cqiC", "type": "fieldAccess" }
       ],
       "fn": "/",
       "name": "cqi",
       "type": "arithmetic"
      }
     ],
     "select": [
      [
       { "params": [ "cqi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ueRicId", "operator": "=~", "value": "/^$ue$/" }
     ]
    }
   ]
  }
 ]
}