{
 "title": "Cell Monitoring",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "UE",
    "query": "SELECT \"ueId\" FROM (SELECT \"ueId\",\"UeMeasurement.rsrp\" FROM \"df.vector\" WHERE time > now() - 30m )"
   },
   {
    "name": "eNB",
    "query": "SELECT \"cellId\" FROM (SELECT \"cellId\",\"UeMeasurement.rsrp\" FROM \"df.vector\" WHERE time > now() - 30m )"
   }
  ]
 },
 "panels": [
  {
   "title": "Aggregated Downlink Throughput",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "Kbits", "label": "sum(DL Throughput)" }
   ],
   "targets": [
    {
     "alias": "$UE",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cellId" ], "type": "tag" }
     ],
     "measurement": "df.vector",
     "query": "SELECT SUM(\"meanValue\") FROM (SELECT mean(\"value\") as meanValue FROM \"df.dlThroughput\" WHERE (\"ueRicId\" =~ /^$UE$/ AND \"cellId\" =~ /^$eNB$/) AND $timeFilter GROUP BY time($interval), \"cellId\", \"ueRicId\") GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "DschThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ueId", "operator": "=~", "value": "/^$UE$/" },
      { "condition": "AND", "key": "cellId", "operator": "=~", "value": "/^$eNB$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Number of Active UEs",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "df.rsrp",
     "query": "select count(distinct(\"ueId\")) from (select \"ueId\",\"UeMeasurement.rsrp\"  from \"df.vector\" WHERE \"cellId\" =~ /^$eNB$/ AND time > now() - 5s)",
     "select": [
      [
       { "params": [ "/^$eNB$/" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ueRicId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "Average RSRP per eNB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "avg(RSRP)" }
   ],
   "targets": [
    {
     "alias": "$tag_cellId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cellId" ], "type": "tag" }
     ],
     "measurement": "df.vector",
     "query": "SELECT mean(\"value\") FROM \"df.rsrp\" WHERE (\"cellId\" =~ /^$eNB$/ AND \"ueRicId\" =~ /^$UE$/) AND $timeFilter GROUP BY time($__interval), \"cellId\"",
     "select": [
      [
       { "params": [ "UeMeasurement.rsrp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "Aggregated Uplink Throughput",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Kbits", "label": "sum(UL Throughput)" }
   ],
   "targets": [
    {
     "alias": "$tag_cellId",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cellId" ], "type": "tag" }
     ],
     "measurement": "df.vector",
     "query": "SELECT SUM(\"meanValue\") FROM (SELECT mean(\"value\") as meanValue FROM \"df.ulThroughput\" WHERE (\"ueRicId\" =~ /^$UE$/ AND \"cellId\" =~ /^$eNB$/) AND $timeFilter GROUP BY time($interval), \"cellId\", \"ueRicId\") GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "UschThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "ueId", "operator": "=~", "value": "/^$UE$/" },
      { "condition": "AND", "key": "cellId", "operator": "=~", "value": "/^$eNB$/" }
     ]
    }
   ]
  },
  {
   "title": "Average RSRQ per eNB",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "avg(RSRQ)" }
   ],
   "targets": [
    {
     "alias": "$tag_cellId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cellId" ], "type": "tag" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "UeMeasurement.rsrq" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "Average CQI per channel",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "avg(CQI per channel)" }
   ],
   "targets": [
    {
     "alias": "CH0",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.0" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.1" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.2" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.3" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.4" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.5" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.6" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH7",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.7" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH8",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.8" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH9",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.9" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.10" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH11",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.11" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    },
    {
     "alias": "CH12",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "df.vector",
     "select": [
      [
       { "params": [ "cqiMeasurement.12" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Wideband CQI per eNB",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "avg(Wideband CQI)" }
   ],
   "targets": [
    {
     "alias": "$tag_cellId",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "cellId" ], "type": "tag" }
     ],
     "measurement": "df.vector",
     "query": "SELECT mean(\"value\") FROM \"df.vector\" WHERE (\"cellId\" =~ /^$eNB$/ AND \"ueRicId\" =~ /^$UE$/) AND $timeFilter GROUP BY time($__interval), \"cellId\"",
     "select": [
      [
       { "params": [ "WidebandCqi" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "cellId", "operator": "=~", "value": "/^$eNB$/" },
      { "condition": "AND", "key": "ueId", "operator": "=~", "value": "/^$UE$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Downlink BLER per eNB",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "percent", "label": "avg(DL BLER)" }
   ],
   "targets": [
    {
     "alias": "$tag_cellId",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cellId" ], "type": "tag" }
     ],
     "measurement": "df.vector",
     "query": "SELECT mean(\"value\") FROM \"df.dlThroughput\" WHERE (\"cellId\" = 'select tag value') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "DownlinkBler" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ueId", "operator": "=~", "value": "/^$UE$/" },
      { "condition": "AND", "key": "cellId", "operator": "=~", "value": "/^$eNB$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Uplink BLER per eNB",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "percent", "label": "avg(UL BLER)" }
   ],
   "targets": [
    {
     "alias": "$tag_cellId",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "cellId" ], "type": "tag" }
     ],
     "measurement": "df.vector",
     "query": "SELECT mean(\"value\") FROM \"df.dlThroughput\" WHERE (\"cellId\" = 'select tag value') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "UplinkBler" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "ueId", "operator": "=~", "value": "/^$UE$/" },
      { "condition": "AND", "key": "cellId", "operator": "=~", "value": "/^$eNB$/" }
     ]
    }
   ]
  }
 ]
}